[program:pixaproof-prod-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /home/deployer/pixaproof-laravel/current/artisan queue:work --queue=default --sleep=3 --tries=3 --timeout=120
autostart=true
autorestart=true
user=www-data
umask=0002
numprocs=1
redirect_stderr=true
stdout_logfile=/home/deployer/pixaproof-laravel/log/worker.log
stopwaitsecs=130
