#!/usr/bin/env python3
"""Sort every tracked file by who wrote it.

    python3 DEV_FILES/wiki/provenance.py [--laravel DIR] [--statamic DIR]

Compares each file in `git ls-files` with two stock installs and with the
installed packages, and writes DEV_FILES/wiki/provenance.json (read by
build.py for page 0b). Origins:

    L  Laravel skeleton file           (laravel/laravel 13.x)
    S  Statamic file                   (statamic/statamic blank site, or published from statamic/cms)
    A  A package's file                (published or generated by an addon)
    C  Written in this repo

Status says how the file relates to its origin:

    stock      byte-identical to the stock copy
    edited     same path as a stock file, contents changed here
    published  copied out of a package by vendor:publish or an install command (maybe reformatted by Pint)
    generated  written by a package's command (named in `reason`)
    custom     no stock counterpart

Stock installs (rebuild them if /tmp was cleared):

    composer create-project laravel/laravel:^13.0 /tmp/baseline-laravel
    composer create-project statamic/statamic /tmp/baseline-statamic
"""

import argparse
import hashlib
import json
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent / "provenance.json"

# Packages whose files may be published into the repo, with the origin badge they carry.
PACKAGES = {
    "vendor/statamic/cms": "S",
    "vendor/statamic/eloquent-driver": "A",
    "vendor/jotham-lec/statamic-marketing-toolkit": "A",
    "vendor/laravel/framework": "L",
    "vendor/laravel/boost": "A",
}

# Files written by a command rather than copied; content can't be matched, so they are named.
GENERATED = {
    "please": ("S", "php artisan statamic:install"),
    "resources/blueprints/globals/seo.yaml": ("A", "php please seo:install (Marketing Toolkit)"),
    "resources/users/groups.yaml": ("S", "php artisan statamic:install"),
    "resources/users/roles.yaml": ("S", "php artisan statamic:install"),
    "AGENTS.md": ("A", "php artisan boost:update (bottom half); the top half is written here"),
    "boost.json": ("A", "php artisan boost:install / boost:update"),
    ".mcp.json": ("A", "php artisan boost:install"),
}

# Path prefixes created empty by an install command.
GENERATED_PREFIXES = {
    "content/": ("S", "php artisan statamic:install (empty content folders)"),
    "storage/statamic/": ("S", "php artisan statamic:install"),
    ".claude/skills/tailwindcss-development/": ("A", "php artisan boost:update"),
    ".claude/skills/infer-conventions/": ("A", "php artisan boost:update"),
    ".claude/skills/laravel-best-practices/": ("A", "php artisan boost:update"),
    ".claude/skills/testing-best-practices/": ("A", "php artisan boost:update"),
}


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def package_index() -> dict[str, tuple[str, str]]:
    """sha256 → (origin, package path) for every publishable file in the packages."""
    index: dict[str, tuple[str, str]] = {}
    for package, origin in PACKAGES.items():
        base = ROOT / package
        if not base.exists():
            continue
        for file in base.rglob("*"):
            if file.is_file() and file.suffix in {".php", ".stub", ".yaml", ".yml", ".json", ".md"}:
                index.setdefault(digest(file), (origin, str(file.relative_to(ROOT))))
    return index


def package_names(index: dict[str, tuple[str, str]]) -> dict[str, tuple[str, str]]:
    """Published config and migration file names → (origin, package path), for files Pint reformatted."""
    names: dict[str, tuple[str, str]] = {}
    for origin, path in index.values():
        if "/config/" in path or "/database/migrations/" in path or path.endswith(".stub"):
            names.setdefault(Path(path).name.removesuffix(".stub"), (origin, path))
    return names


def classify(path: str, laravel: Path, statamic: Path, index, names) -> dict:
    file = ROOT / path
    entry = {"path": path}

    if path in GENERATED:
        origin, reason = GENERATED[path]
        return entry | {"origin": origin, "status": "generated", "reason": reason}
    for prefix, (origin, reason) in GENERATED_PREFIXES.items():
        if path.startswith(prefix):
            return entry | {"origin": origin, "status": "generated", "reason": reason}

    for origin, base in (("L", laravel), ("S", statamic)):
        stock = base / path
        if stock.is_file():
            if digest(stock) == digest(file):
                return entry | {"origin": origin, "status": "stock", "reason": f"identical to {base.name}"}

    for origin, base in (("L", laravel), ("S", statamic)):
        if (base / path).is_file():
            return entry | {"origin": origin, "status": "edited", "reason": f"changed from {base.name}"}

    match = index.get(digest(file))
    if match:
        return entry | {"origin": match[0], "status": "published", "reason": match[1]}

    published_name = file.name
    if path.startswith("database/migrations/"):
        published_name = file.name.split("_", 4)[-1]
    if (path.startswith("config/") or path.startswith("database/migrations/")) and published_name in names:
        origin, source = names[published_name]
        return entry | {"origin": origin, "status": "published", "reason": f"{source} (reformatted or edited)"}

    return entry | {"origin": "C", "status": "custom", "reason": ""}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--laravel", default="/tmp/baseline-laravel", type=Path)
    parser.add_argument("--statamic", default="/tmp/baseline-statamic", type=Path)
    args = parser.parse_args()

    for base in (args.laravel, args.statamic):
        if not (base / "composer.json").exists():
            sys.exit(f"missing stock install: {base} (see the docstring to rebuild it)")

    files = subprocess.run(["git", "ls-files"], cwd=ROOT, check=True, capture_output=True, text=True).stdout.split()
    files = [f for f in files if (ROOT / f).is_file()]

    index = package_index()
    names = package_names(index)
    results = [classify(f, args.laravel, args.statamic, index, names) for f in sorted(files)]

    OUT.write_text(json.dumps(results, indent=1) + "\n")

    counts = Counter((r["origin"], r["status"]) for r in results)
    for (origin, status), count in sorted(counts.items()):
        print(f"{origin}  {status:<10} {count}")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(results)} files)")


if __name__ == "__main__":
    main()
